/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.adnuntius.challenge;

public class App {
        public static void main(String[] args) {
        try {
            MedicineString ms = new MedicineString("86FASc73541_M_1058");
            System.out.println(ms.serialize());
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}
